---
swagger: "2.0"
info:
  version: "2017-07-25T19:54:43Z"
  title: "ShoeShop"
host: "y63gt4on88.execute-api.us-west-2.amazonaws.com"
basePath: "/Dev"
schemes:
- "https"
paths:
  /shoes:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:615275379173:function:getInventory/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"